baseurl = "https://oleng.github.io/"
languageCode = "en-us"
title = "oleng"
theme = [ "lithiumx" ]
googleAnalytics = "UA-155567382-1"
disqusShortname = ""
disableKinds = ["section", "404"]
tags = [ "dev", "python", "ux", "writing", "learning", "postproduction","data" ]
enableEmoji = true

[permalinks]
    blog = "/:year/:month/:day/:title/"
    page = "/:title"

[[menu.main]]
    name = "about"
    url = "/about"
[[menu.main]]
    name = "code"
    url = "https://github.com/oleng"
# [[menu.main]]
#     name = "twitter"
#     url = "https://mobile.twitter.com/deadvoid"


[params]
    mainSections = ["blog"]

    description = "intersections, subcontexts, hubris"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
        url = "logo.png"
        width = 50
        height = 50
        alt = "logoish"

    [params.icon]
        url = "favicon.ico"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = false
            xHTML = false
        [markup.highlight]
            codeFences = true
            guessSyntax = false
            hl_Lines = ""
            lineNoStart = 1
            lineNos = false
            lineNumbersInTable = true
            noClasses = true
            style = "monokailight"
            tabWidth = 4
            [markup.tableOfContents]
            endLevel = 3
            ordered = false
            startLevel = 2
    [markup.blackFriday]
        angledQuotes = false
        footnoteAnchorPrefix = ""
        footnoteReturnLinkContents = ""
        fractions = true
        hrefTargetBlank = false
        latexDashes = true
        nofollowLinks = false
        noreferrerLinks = false
        plainIDAnchors = true
        skipHTML = false
        smartDashes = true
        smartypants = true
        smartypantsQuotesNBSP = false
        taskLists = true