version: '3'
services:

    server:
        image: klakegg/hugo:0.62.1-ext-alpine
        command: server --verbose --verboseLog --gc -t lithiumx
        volumes:
            - ./:/src
            - ./public:/target
        ports:
            - 1313:1313
        container_name: hugo

