name: Hugo

on:
  push:
    branches:
    - hugo

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2


    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.3'
        extended: true

    - name: Build
      run: hugo -v

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public

    - name: Check gh-pages env
      run: |
        echo ${{ GITHUB_JOB }}
        echo ${{ GITHUB_REF }}
        echo ${{ GITHUB_SHA }}
        echo ${{ GITHUB_REPOSITORY }}
        echo ${{ GITHUB_REPOSITORY_OWNER }}
        echo ${{ GITHUB_RUN_ID }}
        echo ${{ GITHUB_RUN_NUMBER }}
        echo ${{ GITHUB_ACTOR }}
        echo ${{ GITHUB_WORKFLOW }}
        echo ${{ GITHUB_HEAD_REF }}
        echo ${{ GITHUB_BASE_REF }}
        echo ${{ GITHUB_EVENT_NAME }}

