name: Hugo Workflow (build, deploy & mirror)

on:
  push:
    branches:
    - hugo

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      PUBLISH_BRANCH: master
      PUBLISH_DIR: ./public

    steps:
    - name: Setup Hugo
      id: hugosetup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.3'
        extended: true

    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

    - name: Build
      id: hugobuild
      run: hugo -v

    - name: Deploy with peaceiris/actions-gh-pages@v2
      id: deployment
      uses: peaceiris/actions-gh-pages@v2

      # changed on < v.3, will be part of env: `keep_files: true`
      with:
        keepFiles: true

    # Send `repository_dispatch` event to `/repos/deadvoid/deadvoid.github.io/dispatches` hook endpoint to trigger build mirror workflow
    - name: Post repository_dispatch event
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.EXT_REPO_PAT }}
        repository: deadvoid/deadvoid.github.io
        event-type: build-mirror
        client-payload: '{"repository": "${{ github.repository }}", "branch": "${{ env.PUBLISH_BRANCH }}"}'
