name: Hugo Workflow (build, deploy & mirror)

on:
  push:
    branches:
    - hugo

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.3'
        extended: true

    - name: Build
      run: hugo -v

    - name: Deploy
      id: deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
      # changed on v.3+: will be part of env: keep_files: true
      with:
        keepFiles: true

    - name: Get master
      if: success()
      run: |
        echo "${{ deploy.env.PUBLISH_BRANCH }}"
        git checkout "${{ deploy.env.PUBLISH_BRANCH }}"
        echo "${{ github.ref }}"
        echo "${{ github.sha }}"
        echo "${{ github.repository }}"
        echo $PWD


    # # Send `repository_dispatch` event to `/repos/deadvoid/deadvoid.github.io/dispatches` hook endpoint to trigger build mirror workflow
    # - name: Dispatch event
    #   if: success()
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.EXT_REPO_PAT }}
    #     repository: deadvoid/deadvoid.github.io
    #     event-type: build-mirror
    #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }} "}'
